export const RestaurantsPageData = [
  {
    name: "Maison Doré",
    location: "Maadi",
    vibe: "Luxury",
    rating: 4.8,
    slug: "maison-dore",
    image: `${import.meta.env.BASE_URL}restaurant-images/Maison-Dore.jpg`,
    map: `${import.meta.env.BASE_URL}restaurant-images/sample-map.png`,
    openingTime: "12",
    closingTime: "23",
  },
  {
    name: "Nobu",
    location: "Dubai",
    vibe: "Japanese Fine Dining",
    rating: 4.9,
    slug: "nobu",
    image: `${import.meta.env.BASE_URL}restaurant-images/Nobu.jpg`,
    openingTime: "18",
    closingTime: "01",
  },
  {
    name: "Auric",
    location: "New Cairo",
    vibe: "Modern Mediterranean",
    rating: 4.7,
    slug: "auric",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    openingTime: "13",
    closingTime: "23",
  },
  {
    name: "Pier88",
    location: "Alexandria",
    vibe: "Sea View Dining",
    rating: 4.6,
    slug: "pier88",
    image: `${import.meta.env.BASE_URL}restaurant-images/Pier88.webp`,
    openingTime: "13",
    closingTime: "00",
  },
  {
    name: "Sachi",
    location: "New Cairo",
    vibe: "Asian Fusion & Fine Dining",
    rating: 4.7,
    slug: "sachi-park-st",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80",
    openingTime: "14",
    closingTime: "00",
  },
  {
    name: "Izakaya",
    location: "Sheikh Zayed",
    vibe: "Nikkei & Contemporary Dining",
    rating: 4.8,
    slug: "izakaya",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    openingTime: "13",
    closingTime: "01",
  },
  {
    name: "Kazoku",
    location: "New Cairo",
    vibe: "Modern Japanese Gastronomy",
    rating: 4.6,
    slug: "kazoku",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    openingTime: "14",
    closingTime: "23:30",
  },
  {
    name: "Revolver",
    location: "Zamalek",
    vibe: "Speakeasy & Open Flame Dining",
    rating: 4.5,
    slug: "revolver",
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80",
    openingTime: "17",
    closingTime: "02",
  },
  {
    name: "Baky Hospitality - Lexie's",
    location: "New Cairo",
    vibe: "Modern Italian Elegance",
    rating: 4.7,
    slug: "lexies",
    image: "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80",
    openingTime: "13",
    closingTime: "23",
  },
  {
    name: "Zuma",
    location: "Riyadh",
    vibe: "Contemporary Japanese",
    rating: 4.9,
    slug: "zuma-riyadh",
    image: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80",
    openingTime: "",
    closingTime: "00",
  },
  {
    name: "Smokery",
    location: "El Gouna",
    vibe: "Yacht Club Lounge & Grill",
    rating: 4.6,
    slug: "the-smokery-gouna",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    openingTime: "12",
    closingTime: "01",
  },
  {
    name: "Crimson Bar & Grill",
    location: "Zamalek",
    vibe: "Nile River View & Steakhouse",
    rating: 4.5,
    slug: "crimson-zamalek",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    openingTime: "15",
    closingTime: "01:30",
  },
  {
    name: "Coya",
    location: "Doha",
    vibe: "Ultra-Luxury Peruvian",
    rating: 4.8,
    slug: "coya-doha",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    openingTime: "",
    closingTime: "00",
  }
];
