export const RestaurantsPageData = [
    {
        name: "Maison Doré",
        location: "Maadi",
        vibe: "Luxury",
        slug: "maison-dore",
        image: "/restaurant-images/Maison-Dore.jpg",
    },
    {
        name: "Nobu",
        location: "Dubai",
        vibe: "Japanese Fine Dining",
        slug: "nobu",
        image: "/restaurant-images/Nobu.jpg",
    },
    {
        name: "Pier88",
        location: "Alexandria",
        vibe: "Sea View Dining",
        slug: "pier88",
        image: "/restaurant-images/Pier88.webp",
    },
    {
        name: "Sachi",
        location: "New Cairo",
        vibe: "Asian Fusion & Fine Dining",
        slug: "sachi-park-st",
        image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Izakaya",
        location: "Sheikh Zayed",
        vibe: "Nikkei & Contemporary Dining",
        slug: "izakaya",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Kazoku",
        location: "New Cairo",
        vibe: "Modern Japanese Gastronomy",
        slug: "kazoku",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Revolver",
        location: "Zamalek",
        vibe: "Speakeasy & Open Flame Dining",
        slug: "revolver",
        image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Baky Hospitality - Lexie's",
        location: "New Cairo",
        vibe: "Modern Italian Elegance",
        slug: "lexies",
        image: "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Zuma",
        location: "Riyadh",
        vibe: "Contemporary Japanese",
        slug: "zuma-riyadh",
        image: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Smokery",
        location: "El Gouna",
        vibe: "Yacht Club Lounge & Grill",
        slug: "the-smokery-gouna",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Crimson Bar & Grill",
        location: "Zamalek",
        vibe: "Nile River View & Steakhouse",
        slug: "crimson-zamalek",
        image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    },
    {
        name: "Coya",
        location: "Doha",
        vibe: "Ultra-Luxury Peruvian",
        slug: "coya-doha",
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    }
];